name: temp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - at-spi2-atk
  - at-spi2-core
  - atk-1.0
  - boost
  - boost-cpp
  - bzip2
  - ca-certificates
  - cairo
  - cairomm
  - cairomm-1.0
  - certifi
  - cffi
  - cycler
  - dbus
  - epoxy
  - expat
  - fontconfig
  - freetype
  - fribidi
  - gdk-pixbuf
  - gettext
  - glib
  - gmp
  - gobject-introspection
  - graph-tool
  - graphite2
  - gtk3
  - harfbuzz
  - hicolor-icon-theme
  - icu
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcups
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libopenblas
  - libpng
  - librsvg
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib-base
  - ncurses
  - numpy
  - olefile
  - openssl
  - pango
  - pcre
  - pillow
  - pip
  - pixman
  - pthread-stubs
  - pycairo
  - pycparser
  - pygobject
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - readline
  - scipy
  - setuptools
  - sigcpp-2.0
  - six
  - sparsehash
  - sqlite
  - tk
  - tornado
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstandard
  - zstd
