name: graphtool
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - at-spi2-atk
  - at-spi2-core
  - atk
  - atk-1.0
  - attrs
  - backcall
  - bleach
  - boost
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - cairomm
  - cairomm-1.0
  - certifi
  - cffi
  - chardet
  - cryptography
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - epoxy
  - expat
  - fontconfig
  - freetype
  - fribidi
  - gdk-pixbuf
  - gettext
  - glib
  - gmp
  - gobject-introspection
  - graph-tool
  - graphite2
  - gst-plugins-base
  - gstreamer
  - gtk3
  - harfbuzz
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - krb5
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libcroco
  - libcups
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - liblapack
  - libllvm9
  - libopenblas
  - libpng
  - librsvg
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib-base
  - mistune
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - nspr
  - nss
  - numpy
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - pthread-stubs
  - ptyprocess
  - pycairo
  - pycparser
  - pygments
  - pygobject
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - scipy
  - send2trash
  - setuptools
  - sigcpp-2.0
  - six
  - sparsehash
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd

