name: temp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.38.0
  - atk-1.0=2.36.0
  - boost=1.72.0
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cairomm=1.12.2
  - cairomm-1.0=1.12.2
  - certifi=2020.12.5
  - cffi=1.14.4
  - cycler=0.10.0
  - dbus=1.13.6
  - epoxy=1.5.4
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.2
  - gettext=0.19.8.1
  - glib=2.66.3
  - gmp=6.2.1
  - gobject-introspection=1.66.1
  - graph-tool=2.35
  - graphite2=1.3.13
  - gtk3=3.24.24
  - harfbuzz=2.7.2
  - hicolor-icon-theme=0.17
  - icu=67.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.2.12
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - librsvg=2.50.2
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib-base=3.3.3
  - ncurses=6.2
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1h
  - pango=1.42.4
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycairo=1.20.0
  - pycparser=2.20
  - pygobject=3.38.0
  - pyparsing=2.4.7
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - readline=8.0
  - scipy=1.5.3
  - setuptools=49.6.0
  - sigcpp-2.0=2.10.3
  - six=1.15.0
  - sparsehash=2.0.3
  - sqlite=3.34.0
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstandard=0.14.1
  - zstd=1.4.5
